#!/usr/bin/env bash

#set -o xtrace
set -e

fatal() {
    echo "$@" >&2
    exit 1
}

# Function to detect if the system has a GUI
# Returns 0 if the system has a GUI, 1 otherwise
has_gui() {
  # We consider the system to have a GUI if the DISPLAY or WAYLAND_DISPLAY environment variables are
  # set
  if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
    return 0
  fi

  # We consider the system to have a GUI if at least 10 GUI packages are installed
  count=$(dpkg -l | grep -E '^ii\s+(xorg|xserver|wayland|gnome|kde|xfce|lxde|mate|plasma)' | wc -l)
  if [ "$count" -ge 10 ]; then
    return 0
  fi

  return 1
}

cd $(cd $(dirname "$0") && pwd)

if [ "$(id -u)" -ne 0 ]; then
  ELEVATE="sudo"

  if ! command -v sudo &>/dev/null; then
    fatal "ERROR: sudo binary not found. Please install sudo."
  fi
else
  ELEVATE=""
fi

if ! command -v docker &>/dev/null; then
  fatal "ERROR: docker binary not found. Please install the Docker engine."
elif [ -f /.dockerenv ]; then
  fatal "ERROR: cannot run this script from within a Docker container."
elif ! docker ps &> /dev/null; then
  DOCKER="sudo docker"
else
  DOCKER="docker"
fi

if ! command -v make &>/dev/null; then
  fatal "ERROR: make command not found. Please install make."
fi

if [ -z "$TARGET_ENV" ]; then
  if has_gui; then
    TARGET_ENV=x
  else
    TARGET_ENV=term
  fi
fi

source ./env.sh
export TARGET_ENV

$DOCKER compose --progress plain \
        run \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd) \
        builder

( cd emacs && $ELEVATE make install )

echo "done."
