services:
  builder:
    image: emacs-builder
    build:
      dockerfile: Dockerfile
      pull: true
    environment:
      TARGET_ENV: ${TARGET_ENV}
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    entrypoint: ./entrypoint.sh
